version: '3.8'

services:
  nginx:
    build: ./frontend
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/usr/src/server
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run start"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - ./mongodb.env
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    env_file:
      - ./mongo-express.env
    depends_on:
      - mongo

volumes:
  mongo-data:
